export interface IHumanAttributes {
  intelligence: number;
  empathy: number;
  creativity: number;
  sociability: number;
  resilience: number;
  curiosity: number;
  adaptability: number;
  motivation: number;
  integrity: number;
  leadership: number;
}

export interface INodeData {
  id: number;
  name: string;
  position: [number, number, number];
  isCentral: boolean;
  color: string;
  attributes: IHumanAttributes;
  preferences: IHumanAttributes;
}

export const nodeData: INodeData[] = [
  {
    id: 1,
    name: 'James',
    position: [0, 0, 0],
    isCentral: true,
    color: '#FF5733',
    attributes: {
      intelligence: 85,
      empathy: 40,
      creativity: 70,
      sociability: 65,
      resilience: 80,
      curiosity: 75,
      adaptability: 60,
      motivation: 90,
      integrity: 85,
      leadership: 70,
    },
    preferences: {
      intelligence: 70,
      empathy: 60,
      creativity: 75,
      sociability: 80,
      resilience: 65,
      curiosity: 80,
      adaptability: 70,
      motivation: 85,
      integrity: 90,
      leadership: 65,
    },
  },
  {
    id: 2,
    name: 'John',
    position: [2, 1, -1],
    isCentral: false,
    color: '#33FF57',
    attributes: {
      intelligence: 78,
      empathy: 55,
      creativity: 62,
      sociability: 70,
      resilience: 75,
      curiosity: 68,
      adaptability: 72,
      motivation: 80,
      integrity: 82,
      leadership: 60,
    },
    preferences: {
      intelligence: 65,
      empathy: 70,
      creativity: 70,
      sociability: 65,
      resilience: 80,
      curiosity: 75,
      adaptability: 68,
      motivation: 75,
      integrity: 85,
      leadership: 70,
    },
  },
  {
    id: 3,
    name: 'Alice',
    position: [-3, 2, 1],
    isCentral: false,
    color: '#3357FF',
    attributes: {
      intelligence: 92,
      empathy: 78,
      creativity: 88,
      sociability: 82,
      resilience: 85,
      curiosity: 90,
      adaptability: 75,
      motivation: 88,
      integrity: 95,
      leadership: 80,
    },
    preferences: {
      intelligence: 80,
      empathy: 70,
      creativity: 75,
      sociability: 90,
      resilience: 80,
      curiosity: 85,
      adaptability: 70,
      motivation: 80,
      integrity: 90,
      leadership: 75,
    },
  },
  {
    id: 4,
    name: 'Robert',
    position: [4, -1, 2],
    isCentral: false,
    color: '#F1C40F',
    attributes: {
      intelligence: 65,
      empathy: 45,
      creativity: 55,
      sociability: 50,
      resilience: 60,
      curiosity: 58,
      adaptability: 62,
      motivation: 70,
      integrity: 68,
      leadership: 50,
    },
    preferences: {
      intelligence: 70,
      empathy: 55,
      creativity: 60,
      sociability: 65,
      resilience: 75,
      curiosity: 65,
      adaptability: 68,
      motivation: 72,
      integrity: 70,
      leadership: 55,
    },
  },
  {
    id: 5,
    name: 'Emma',
    position: [-2, -3, -2],
    isCentral: false,
    color: '#FF33A8',
    attributes: {
      intelligence: 88,
      empathy: 82,
      creativity: 90,
      sociability: 85,
      resilience: 80,
      curiosity: 87,
      adaptability: 75,
      motivation: 85,
      integrity: 90,
      leadership: 78,
    },
    preferences: {
      intelligence: 80,
      empathy: 90,
      creativity: 85,
      sociability: 80,
      resilience: 85,
      curiosity: 80,
      adaptability: 82,
      motivation: 80,
      integrity: 95,
      leadership: 70,
    },
  },
  {
    id: 6,
    name: 'Michael',
    position: [1, 2, 3],
    isCentral: false,
    color: '#33FFF5',
    attributes: {
      intelligence: 75,
      empathy: 50,
      creativity: 65,
      sociability: 60,
      resilience: 70,
      curiosity: 55,
      adaptability: 60,
      motivation: 68,
      integrity: 72,
      leadership: 55,
    },
    preferences: {
      intelligence: 70,
      empathy: 65,
      creativity: 70,
      sociability: 75,
      resilience: 65,
      curiosity: 60,
      adaptability: 70,
      motivation: 72,
      integrity: 75,
      leadership: 60,
    },
  },
  {
    id: 7,
    name: 'Sophia',
    position: [-1, -2, 3],
    isCentral: false,
    color: '#FFA500',
    attributes: {
      intelligence: 82,
      empathy: 90,
      creativity: 78,
      sociability: 88,
      resilience: 85,
      curiosity: 80,
      adaptability: 78,
      motivation: 85,
      integrity: 88,
      leadership: 70,
    },
    preferences: {
      intelligence: 75,
      empathy: 80,
      creativity: 82,
      sociability: 90,
      resilience: 80,
      curiosity: 85,
      adaptability: 75,
      motivation: 80,
      integrity: 90,
      leadership: 75,
    },
  },
  {
    id: 8,
    name: 'William',
    position: [3, -2, 1],
    isCentral: false,
    color: '#800080',
    attributes: {
      intelligence: 68,
      empathy: 55,
      creativity: 60,
      sociability: 50,
      resilience: 65,
      curiosity: 60,
      adaptability: 58,
      motivation: 62,
      integrity: 70,
      leadership: 55,
    },
    preferences: {
      intelligence: 60,
      empathy: 60,
      creativity: 65,
      sociability: 55,
      resilience: 70,
      curiosity: 65,
      adaptability: 60,
      motivation: 68,
      integrity: 75,
      leadership: 60,
    },
  },
  {
    id: 9,
    name: 'Olivia',
    position: [-4, 1, -3],
    isCentral: false,
    color: '#008000',
    attributes: {
      intelligence: 90,
      empathy: 65,
      creativity: 85,
      sociability: 75,
      resilience: 80,
      curiosity: 78,
      adaptability: 70,
      motivation: 82,
      integrity: 88,
      leadership: 60,
    },
    preferences: {
      intelligence: 85,
      empathy: 75,
      creativity: 80,
      sociability: 80,
      resilience: 78,
      curiosity: 82,
      adaptability: 75,
      motivation: 80,
      integrity: 90,
      leadership: 65,
    },
  },
  {
    id: 10,
    name: 'David',
    position: [2, 3, -4],
    isCentral: false,
    color: '#FFC0CB',
    attributes: {
      intelligence: 78,
      empathy: 72,
      creativity: 80,
      sociability: 76,
      resilience: 70,
      curiosity: 75,
      adaptability: 68,
      motivation: 80,
      integrity: 77,
      leadership: 65,
    },
    preferences: {
      intelligence: 75,
      empathy: 78,
      creativity: 70,
      sociability: 80,
      resilience: 72,
      curiosity: 75,
      adaptability: 70,
      motivation: 75,
      integrity: 80,
      leadership: 70,
    },
  },
  {
    id: 11,
    name: 'Emily',
    position: [-3, -1, 2],
    isCentral: false,
    color: '#A52A2A',
    attributes: {
      intelligence: 85,
      empathy: 88,
      creativity: 82,
      sociability: 80,
      resilience: 78,
      curiosity: 84,
      adaptability: 75,
      motivation: 80,
      integrity: 90,
      leadership: 70,
    },
    preferences: {
      intelligence: 80,
      empathy: 85,
      creativity: 80,
      sociability: 85,
      resilience: 75,
      curiosity: 80,
      adaptability: 78,
      motivation: 82,
      integrity: 88,
      leadership: 75,
    },
  },
  {
    id: 12,
    name: 'Daniel',
    position: [5, 0, -1],
    isCentral: false,
    color: '#808080',
    attributes: {
      intelligence: 70,
      empathy: 65,
      creativity: 68,
      sociability: 60,
      resilience: 72,
      curiosity: 66,
      adaptability: 70,
      motivation: 68,
      integrity: 75,
      leadership: 60,
    },
    preferences: {
      intelligence: 68,
      empathy: 70,
      creativity: 65,
      sociability: 68,
      resilience: 70,
      curiosity: 72,
      adaptability: 65,
      motivation: 70,
      integrity: 80,
      leadership: 62,
    },
  },
  {
    id: 13,
    name: 'Mia',
    position: [-5, 2, 0],
    isCentral: false,
    color: '#FFD700',
    attributes: {
      intelligence: 75,
      empathy: 80,
      creativity: 70,
      sociability: 85,
      resilience: 78,
      curiosity: 82,
      adaptability: 80,
      motivation: 85,
      integrity: 90,
      leadership: 65,
    },
    preferences: {
      intelligence: 80,
      empathy: 75,
      creativity: 85,
      sociability: 80,
      resilience: 85,
      curiosity: 80,
      adaptability: 78,
      motivation: 82,
      integrity: 88,
      leadership: 70,
    },
  },
  {
    id: 14,
    name: 'Ethan',
    position: [1, -4, 3],
    isCentral: false,
    color: '#40E0D0',
    attributes: {
      intelligence: 80,
      empathy: 70,
      creativity: 75,
      sociability: 68,
      resilience: 72,
      curiosity: 70,
      adaptability: 65,
      motivation: 78,
      integrity: 80,
      leadership: 70,
    },
    preferences: {
      intelligence: 75,
      empathy: 75,
      creativity: 70,
      sociability: 75,
      resilience: 70,
      curiosity: 75,
      adaptability: 70,
      motivation: 75,
      integrity: 75,
      leadership: 70,
    },
  },
  {
    id: 15,
    name: 'Charlotte',
    position: [-2, 4, -1],
    isCentral: false,
    color: '#EE82EE',
    attributes: {
      intelligence: 88,
      empathy: 82,
      creativity: 80,
      sociability: 78,
      resilience: 85,
      curiosity: 80,
      adaptability: 75,
      motivation: 82,
      integrity: 90,
      leadership: 68,
    },
    preferences: {
      intelligence: 80,
      empathy: 85,
      creativity: 75,
      sociability: 80,
      resilience: 80,
      curiosity: 78,
      adaptability: 80,
      motivation: 80,
      integrity: 88,
      leadership: 70,
    },
  },
  {
    id: 16,
    name: 'Alexander',
    position: [3, 2, -5],
    isCentral: false,
    color: '#F5F5DC',
    attributes: {
      intelligence: 65,
      empathy: 60,
      creativity: 62,
      sociability: 55,
      resilience: 70,
      curiosity: 60,
      adaptability: 68,
      motivation: 66,
      integrity: 70,
      leadership: 60,
    },
    preferences: {
      intelligence: 62,
      empathy: 65,
      creativity: 60,
      sociability: 62,
      resilience: 68,
      curiosity: 65,
      adaptability: 62,
      motivation: 64,
      integrity: 72,
      leadership: 62,
    },
  },
  {
    id: 17,
    name: 'Amelia',
    position: [-4, -3, 4],
    isCentral: false,
    color: '#7FFFD4',
    attributes: {
      intelligence: 78,
      empathy: 75,
      creativity: 80,
      sociability: 70,
      resilience: 72,
      curiosity: 78,
      adaptability: 75,
      motivation: 80,
      integrity: 85,
      leadership: 70,
    },
    preferences: {
      intelligence: 75,
      empathy: 80,
      creativity: 75,
      sociability: 78,
      resilience: 70,
      curiosity: 80,
      adaptability: 75,
      motivation: 75,
      integrity: 80,
      leadership: 70,
    },
  },
  {
    id: 18,
    name: 'Benjamin',
    position: [0, 5, -2],
    isCentral: false,
    color: '#D2691E',
    attributes: {
      intelligence: 82,
      empathy: 78,
      creativity: 75,
      sociability: 80,
      resilience: 77,
      curiosity: 74,
      adaptability: 70,
      motivation: 75,
      integrity: 80,
      leadership: 68,
    },
    preferences: {
      intelligence: 75,
      empathy: 80,
      creativity: 70,
      sociability: 75,
      resilience: 72,
      curiosity: 75,
      adaptability: 70,
      motivation: 75,
      integrity: 78,
      leadership: 70,
    },
  },
  {
    id: 19,
    name: 'Abigail',
    position: [-1, -5, 1],
    isCentral: false,
    color: '#8A2BE2',
    attributes: {
      intelligence: 88,
      empathy: 85,
      creativity: 80,
      sociability: 82,
      resilience: 80,
      curiosity: 78,
      adaptability: 75,
      motivation: 82,
      integrity: 88,
      leadership: 70,
    },
    preferences: {
      intelligence: 80,
      empathy: 75,
      creativity: 78,
      sociability: 80,
      resilience: 75,
      curiosity: 80,
      adaptability: 78,
      motivation: 80,
      integrity: 85,
      leadership: 75,
    },
  },
  {
    id: 20,
    name: 'Lucas',
    position: [4, 3, -3],
    isCentral: false,
    color: '#DC143C',
    attributes: {
      intelligence: 70,
      empathy: 65,
      creativity: 60,
      sociability: 62,
      resilience: 68,
      curiosity: 64,
      adaptability: 66,
      motivation: 70,
      integrity: 72,
      leadership: 65,
    },
    preferences: {
      intelligence: 68,
      empathy: 70,
      creativity: 65,
      sociability: 68,
      resilience: 70,
      curiosity: 66,
      adaptability: 68,
      motivation: 70,
      integrity: 75,
      leadership: 68,
    },
  },
];
