export interface IHumanAttributes {
  intelligence: number;
  empathy: number;
  creativity: number;
  sociability: number;
  resilience: number;
  curiosity: number;
  adaptability: number;
  motivation: number;
  integrity: number;
  leadership: number;
}

export interface INodeData {
  id: number;
  name: string;
  position: [number, number, number];
  isCentral: boolean;
  color: string;
  attributes: IHumanAttributes;
}

export const nodeData: INodeData[] = [
  {
    id: 1,
    name: 'James',
    position: [0, 0, 0],
    isCentral: true,
    color: '#FF0000',
    attributes: {
      intelligence: 100,
      empathy: 100,
      creativity: 100,
      sociability: 100,
      resilience: 100,
      curiosity: 100,
      adaptability: 100,
      motivation: 100,
      integrity: 100,
      leadership: 100,
    },
  },
  {
    id: 2,
    name: 'John',
    position: [2, 1, -1],
    isCentral: false,
    color: '#00FF00',
    attributes: {
      intelligence: 95,
      empathy: 85,
      creativity: 75,
      sociability: 80,
      resilience: 90,
      curiosity: 85,
      adaptability: 80,
      motivation: 95,
      integrity: 90,
      leadership: 88,
    },
  },
  {
    id: 3,
    name: 'Alice',
    position: [-3, 2, 1],
    isCentral: false,
    color: '#0000FF',
    attributes: {
      intelligence: 70,
      empathy: 60,
      creativity: 80,
      sociability: 75,
      resilience: 70,
      curiosity: 65,
      adaptability: 68,
      motivation: 72,
      integrity: 74,
      leadership: 70,
    },
  },
  {
    id: 4,
    name: 'Robert',
    position: [4, -1, 2],
    isCentral: false,
    color: '#FFFF00',
    attributes: {
      intelligence: 5,
      empathy: 15,
      creativity: 25,
      sociability: 35,
      resilience: 45,
      curiosity: 55,
      adaptability: 65,
      motivation: 75,
      integrity: 85,
      leadership: 95,
    },
  },
  {
    id: 5,
    name: 'Emma',
    position: [-2, -3, -2],
    isCentral: false,
    color: '#FF00FF',
    attributes: {
      intelligence: 11,
      empathy: 22,
      creativity: 33,
      sociability: 44,
      resilience: 55,
      curiosity: 66,
      adaptability: 77,
      motivation: 88,
      integrity: 99,
      leadership: 100,
    },
  },
  {
    id: 6,
    name: 'Michael',
    position: [1, 2, 3],
    isCentral: false,
    color: '#00FFFF',
    attributes: {
      intelligence: 100,
      empathy: 100,
      creativity: 90,
      sociability: 80,
      resilience: 70,
      curiosity: 60,
      adaptability: 50,
      motivation: 40,
      integrity: 30,
      leadership: 20,
    },
  },
  {
    id: 7,
    name: 'Sophia',
    position: [-1, -2, 3],
    isCentral: false,
    color: '#FFA500',
    attributes: {
      intelligence: 20,
      empathy: 30,
      creativity: 40,
      sociability: 50,
      resilience: 60,
      curiosity: 70,
      adaptability: 80,
      motivation: 90,
      integrity: 100,
      leadership: 90,
    },
  },
  {
    id: 8,
    name: 'William',
    position: [3, -2, 1],
    isCentral: false,
    color: '#800080',
    attributes: {
      intelligence: 10,
      empathy: 10,
      creativity: 20,
      sociability: 20,
      resilience: 30,
      curiosity: 30,
      adaptability: 40,
      motivation: 40,
      integrity: 50,
      leadership: 50,
    },
  },
  {
    id: 9,
    name: 'Olivia',
    position: [-4, 1, -3],
    isCentral: false,
    color: '#008000',
    attributes: {
      intelligence: 99,
      empathy: 88,
      creativity: 77,
      sociability: 66,
      resilience: 55,
      curiosity: 44,
      adaptability: 33,
      motivation: 22,
      integrity: 11,
      leadership: 0,
    },
  },
  {
    id: 10,
    name: 'David',
    position: [2, 3, -4],
    isCentral: false,
    color: '#FFC0CB',
    attributes: {
      intelligence: 50,
      empathy: 60,
      creativity: 70,
      sociability: 80,
      resilience: 90,
      curiosity: 100,
      adaptability: 90,
      motivation: 80,
      integrity: 70,
      leadership: 60,
    },
  },
  {
    id: 11,
    name: 'Emily',
    position: [-3, -1, 2],
    isCentral: false,
    color: '#A52A2A',
    attributes: {
      intelligence: 15,
      empathy: 25,
      creativity: 35,
      sociability: 45,
      resilience: 55,
      curiosity: 65,
      adaptability: 75,
      motivation: 85,
      integrity: 95,
      leadership: 100,
    },
  },
  {
    id: 12,
    name: 'Daniel',
    position: [5, 0, -1],
    isCentral: false,
    color: '#808080',
    attributes: {
      intelligence: 0,
      empathy: 10,
      creativity: 20,
      sociability: 30,
      resilience: 40,
      curiosity: 50,
      adaptability: 60,
      motivation: 70,
      integrity: 80,
      leadership: 90,
    },
  },
  {
    id: 13,
    name: 'Mia',
    position: [-5, 2, 0],
    isCentral: false,
    color: '#FFD700',
    attributes: {
      intelligence: 5,
      empathy: 10,
      creativity: 15,
      sociability: 20,
      resilience: 25,
      curiosity: 30,
      adaptability: 35,
      motivation: 40,
      integrity: 45,
      leadership: 50,
    },
  },
  {
    id: 14,
    name: 'Ethan',
    position: [1, -4, 3],
    isCentral: false,
    color: '#40E0D0',
    attributes: {
      intelligence: 50,
      empathy: 50,
      creativity: 50,
      sociability: 50,
      resilience: 50,
      curiosity: 50,
      adaptability: 50,
      motivation: 50,
      integrity: 50,
      leadership: 50,
    },
  },
  {
    id: 15,
    name: 'Charlotte',
    position: [-2, 4, -1],
    isCentral: false,
    color: '#EE82EE',
    attributes: {
      intelligence: 20,
      empathy: 40,
      creativity: 60,
      sociability: 80,
      resilience: 100,
      curiosity: 80,
      adaptability: 60,
      motivation: 40,
      integrity: 20,
      leadership: 0,
    },
  },
  {
    id: 16,
    name: 'Alexander',
    position: [3, 2, -5],
    isCentral: false,
    color: '#F5F5DC',
    attributes: {
      intelligence: 30,
      empathy: 30,
      creativity: 30,
      sociability: 30,
      resilience: 30,
      curiosity: 30,
      adaptability: 30,
      motivation: 30,
      integrity: 30,
      leadership: 30,
    },
  },
  {
    id: 17,
    name: 'Amelia',
    position: [-4, -3, 4],
    isCentral: false,
    color: '#7FFFD4',
    attributes: {
      intelligence: 10,
      empathy: 30,
      creativity: 50,
      sociability: 70,
      resilience: 90,
      curiosity: 70,
      adaptability: 50,
      motivation: 30,
      integrity: 10,
      leadership: 0,
    },
  },
  {
    id: 18,
    name: 'Benjamin',
    position: [0, 5, -2],
    isCentral: false,
    color: '#D2691E',
    attributes: {
      intelligence: 100,
      empathy: 95,
      creativity: 90,
      sociability: 85,
      resilience: 80,
      curiosity: 75,
      adaptability: 70,
      motivation: 65,
      integrity: 60,
      leadership: 55,
    },
  },
  {
    id: 19,
    name: 'Abigail',
    position: [-1, -5, 1],
    isCentral: false,
    color: '#8A2BE2',
    attributes: {
      intelligence: 55,
      empathy: 60,
      creativity: 65,
      sociability: 70,
      resilience: 75,
      curiosity: 80,
      adaptability: 85,
      motivation: 90,
      integrity: 95,
      leadership: 100,
    },
  },
  {
    id: 20,
    name: 'Lucas',
    position: [4, 3, -3],
    isCentral: false,
    color: '#DC143C',
    attributes: {
      intelligence: 0,
      empathy: 0,
      creativity: 10,
      sociability: 10,
      resilience: 20,
      curiosity: 20,
      adaptability: 30,
      motivation: 30,
      integrity: 40,
      leadership: 40,
    },
  },
];
